### ISSUE TITLE
Github CI concurrency seems to cancel runs due to priority quirks

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-vm-examples#65]
In https://github.com/seL4/camkes-vm-examples/actions/runs/7696538606?pr=57 the run "Hardware (nehalem)" was cancelled with the message `Canceling since a higher priority waiting request for 'camkes-hw-pr-0' exists`. There are are few PRs running in parallel and it feels like something in https://github.com/seL4/camkes-vm-examples/pull/60 is still not working as expected. The hardware runs should queue up nicely, but not cancel others other.

**Comment by lsf37** [comment]
If we want to avoid that, we need to encode something like the PR number in the `concurrency` statement [here](https://github.com/seL4/camkes-vm-examples/blob/34f83da178dc14e47748a767bf02322c2e912a54/.github/workflows/test-hw.yml#L79).

This might be as simple as
```
concurrency: camkes-hw-pr-${{ github.event.number }}-${{ strategy.job-index }}
```

**Comment by lsf37** [comment]
(We'd need to check that the event number stays the same when new commits are pushed to the PR)

**Comment by axel-h** [comment]
We could also remove the `concurrency` field. In the kernel Hw run it also does not exist. If the machine queue serialized things that would do. Just for multiple pushed to a PR, having never pushe killing the runs of older one might be useful - or in some cases not as one might want the older runs to finish to see some intermediate results.

**Comment by lsf37** [comment]
> We could also remove the `concurrency` field. In the kernel Hw run it also does not exist. If the machine queue serialized things that would do. 

The idea is to reduce load on the machine queue. It would still run all the old jobs that are not interesting any more and block the boards for other things during that time. If at all, I would want to add this to the kernel HW run as well when it works properly.

> Just for multiple pushed to a PR, having never pushe killing the runs of older one might be useful - or in some cases not as one might want the older runs to finish to see some intermediate results.

For that case (where we do want intermediate results) I think we should then wait with the push instead of pushing multiple times and always processing everything. For some boards there is only one in the machine queue, and multiple PRs can easily amount to > 100 jobs (20-ish per run), which means most of them will just be waiting on lock for a very long time and progress will be slow for most of them.
